### PR TITLE
Fixed Korean translations.

### PR DESCRIPTION
**Pull request by cherryband**
This one(and the future ones until 0.92.1 is available) is done on another computer with Inkscape 0.91 installed, so it's okay to merge.

### CODE REVIEW

**Comment by Deevad** [comment]
Thank you :)

**Comment by Deevad** [comment]
Haha, you also in your pull-request changed the english credit page in [en] folder to Korean accidentaly  xD
I'll fix it :)

**Comment by Deevad** [comment]
Fixed in https://github.com/Deevad/peppercarrot_ep04_translation/commit/43c6f063171c04adce287d19f1235d044ccd85ff  :)

**Comment by cherryband** [comment]
Whoops! Yes both was written in English(untranslated in previous version) so I've mistaken it haha

**Pull request merged**
