### PR TITLE
Danish translation

### PR DESCRIPTION
**Pull request by Alkarex**
Based on French + English + Swedish + Norwegian
https://github.com/Deevad/peppercarrot_ep04_translation/issues/27

### CODE REVIEW

**Comment by Alkarex** [comment]
@Deevad *(Mademoiselle) Safran* should be named *(Frøken) Safran* in Danish, but this requires changing the previous episode (3) in which she is named *(Ms) Saffron*. I can change in both episodes if you want
https://da.wikipedia.org/wiki/Safran

**Comment by Deevad** [comment]
Thank you! That's OK with Safran. 
Translators use this shared document : https://docs.google.com/spreadsheets/d/1zRqVAj8q1iHwOXQBplXp_DaoZyDgJ3uA0_st_iZEDGg/edit#gid=0 to keep consistency on the name accross episodes. Maybe it can help to report her name as well. 

I'll merge and render, it will be online in 30min :)

**Comment by Deevad** [comment]
Quick note: do not hesitate to add your name to the README.md file ; the attribution is based on this file in case a publisher/printer use it.

**Comment by Alkarex** [comment]
Ok, will do in the next pull request, at the same time as fixing Safran's name.
P.S.: I had to copy-paste the "Crr crr" and "Shh shh" from box 10 to box 8, as they were not there by default in box 8

**Comment by Deevad** [comment]
Wow, that was a ★★★ Pull-Request, thank you! 

I just ran the renderfarm and everything rendered without a single error or verbose line on my side.
I'm uploading the page now, they 'll be online in less than 5 min. 

Do you prefer PR workflow ? or would you prefer direct permission to push on master ?

**Comment by Alkarex** [comment]
Thanks :-) I like the PR workflow. I hope one single more pull request should be enough

**Comment by Alkarex** [comment]
Ah, I can see the "Crr crr" and "Shh shh" are there two times in box 8 (they were not in the PNGs). I will fix that at the same time.

**Comment by Deevad** [comment]
Ok. Do not hesitate to make as many PR as you wants/needs. No problem here, merging is just as easy as doing a single click and launching a Bash script. No pain on my side :-)

**Pull request merged**
